apiVersion: apps/v1           
kind: Deployment             
metadata:
  name: toystore-app-server    
  labels:                    
    app: toystore-app-server
spec:
  replicas: 1                 
  selector:
    matchLabels:              
      app: toystore-app-server
  template:                  
    metadata:
      labels:                 
        app: toystore-app-server
    spec:                    
      containers:
      - name: toystore-app-server
        image: amirelgammal/testo3
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080 
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:                 
        - name: SPRING_DATASOURCE_USERNAME 
          valueFrom:          
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: url
---
apiVersion: v1               
kind: Service                
metadata:                     
  name: toystore-app-server   
  labels:                    
    app: toystore-app-server
spec:                         
  type: NodePort             
  selector:
    app: toystore-app-server  
  ports:                      
  - name: http
    port: 8080
    targetPort: 8080