apiVersion: v1
kind: PersistentVolume            
metadata:
  name: spring-pv
  labels:
    type: local
spec:
  storageClassName: standard      
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:                       
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain  
---    
apiVersion: v1
kind: PersistentVolumeClaim        
metadata:                          
  name: spring-pv-claim
  labels:
    app: toystore-app
spec:                              
  storageClassName: standard       
  accessModes:
    - ReadWriteOnce               
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1                   
kind: Service                     
metadata:
  name: toystore-app-mysql         
  labels:                         
    app: toystore-app
spec:
  ports:
    - port: 3306
  selector:                       
    app: toystore-app
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment                    
metadata:
  name: toystore-app-mysql           
  labels:                           
    app: toystore-app
spec:
  selector:
    matchLabels:                    
      app: toystore-app
      tier: mysql
  strategy:
    type: Recreate
  template:                         
    metadata:
      labels:                       
        app: toystore-app
        tier: mysql
    spec:                           
      containers:
      - image: mysql:5.6           
        name: mysql
        env:                       
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:                
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        ports:
        - containerPort: 3306              
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage  
          mountPath: /var/lib/mysql
      volumes:                      
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: spring-pv-claim